id = "mcp-server-grafana"
name = "Grafana MCP Server"
description = "Model Context Protocol Server for Grafana"
version = "0.1.2"
schema_version = 1
authors = ["Ben Sully <ben.sully88@gmail.com>"]
repository = "https://github.com/sd2k/zed-mcp-grafana"

[context_servers.mcp-server-grafana]
name = "Grafana MCP Server"
